language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
services:
- postgresql
install: npm install
before_script: ls node_modules
script: npm test && npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: HPfqUiFyvrazvIoaYoAAq1bCzsBqVoNIz6RP004i4eqA7dty9EuqaVXgf0225o8KvkCtbOPFNfP00Nt9Ut1nluOsia3D6Hj0QXwSlYYFG5UPa/C/TcgfXg+NvTVMH7dNyOBCjamfAG25SKrRpMbNqSOxMtnHb0vyHhVnH3vZdo4erSH8IJT15EwzuFCALrRma0thCTkjHufjKY2QA/VnlWvC3LYr4S/SZCrJqqe4S1z37eUtcB1KuerW2+P9gkqf+EaIQ/SZikwv0cMFWTi8WdQc8AXYZfnuxqCrpJNFJDUDwuuJgIJPx7S4sLb0NXxzV/16ZKC7vMEBRt3dN6XooYokPJLH5OWb/xwcWoVxBWTmg9xeVP91y02IxOzkI0qtbfGOSuUaXbK0Pa0bqFTQhlUgSBH6fVK0/e7c6sbrkE8bnpG0kVsaj+GkCU13V76v1BjtHGMirTJ90vKKPVgLT0qxCyrOI8QqGwCm6WwzdoVh6zEDP30nl1FdFZBo2fxHF+kGBU73JcyzsBIc6owMC+3dq4JGie2eo6z1g07DbVlAAY2iyz993fg56fFpo55lIjPVDsGTo7Ts6hNd5WRZUQUKVUx6sVzdUYN6flJG0goB9O4V55fCwcXqyNDdR/i+YET8exp24QEBAQuVWgrrk8LzU/h1HjOgfuEwUv+4d0M=
  app:
    master: steps-app
  run: npm run seed
